### ISSUE TITLE
[BUG] osu! installer doesn't have internet connection.

### ISSUE THREAD

**Issue by ghost** [yurisuki/osu-install-old#11]
**Describe the issue**
When the installer gets to the install phase, after I got over the "click if you want to change directory", the installer tells me I don't have an internet connection.

**To Reproduce**
1. Run the installer
2. Get to the install phase.
3. Get greeted with an internet connection error
4.

**Screenshots**

**Distribution (OS):**
 - Distribution Arch Linux
 - Kernel version [e.g. 5.0.13-zen1-1-zen] (You can find out using `uname -r`)
 - Version of your osu-install 1.2

**Additional context**
I get this error message immediately after the prompt for my internet connection.
`002e:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0xbf1ed58, 0xb67ae08, 0xbf1ed5c, 0xbf1ed50`

**Comment by ghost** [comment]
As I had to run it another time (ofc deleting wine_osu beforehand) I get another prompt saying "Could not install .NET Framework v4. Click here..." but then I got that message again.

**Comment by yurisuki** [comment]
On 19/05/14 09:10, Gergő Vári wrote:
> **Describe the issue**
> When the installer gets to the install phase, after I got over the "click if you want to change directory", the installer tells me I don't have an internet connection.
>
> **To Reproduce**
> Steps to reproduce the behavior:
> 1. Run the installer
> 2. Get to the install phase.
> 3. Get greeted with an internet connection error
> 4.
>
> **Screenshots**
> If applicable, add screenshots to help explain your problem.
>
> **Distribution (OS):**
>  - Distribution Arch Linux
>  - Kernel version [e.g. 5.0.13-zen1-1-zen] (You can find out using `uname -r`)
>  - Version of your osu-install 1.2
>
> **Additional context**
> I get this error message immediately after the prompt for my internet connection.
> `002e:fixme:nls:GetFileMUIPath stub: 0x10, L"C:\\windows\\system32\\tzres.dll", (null), 0xbf1ed58, 0xb67ae08, 0xbf1ed5c, 0xbf1ed50`
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/yurisuki/osu-install/issues/11
don't change the osu! install dir

**Comment by yurisuki** [comment]
On 19/05/14 09:11, Gergő Vári wrote:
> As I had to run it another time (ofc deleting wine_osu beforehand) I get another prompt saying "Could not install .NET Framework v4. Click here..." but then I got that message again.
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/yurisuki/osu-install/issues/11#issuecomment-492304768
run the script once again without removing ~/.wine_osu

**Comment by ghost** [comment]
I ran it multiple times now, I'm waiting at installing dependencies to wineprefix, so I will report if something new comes up.

**Comment by ghost** [comment]
I think it has to output something at this phase, right? Because it's not really doing anything now.

**Comment by ghost** [comment]
It definitely froze up there.

**Comment by ghost** [comment]
Okay I had to delete the wineprefix again for it to do something.

**Comment by ghost** [comment]
`002a:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub                                                                                                                                                                                     
002a:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
002a:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
002d:fixme:process:SetProcessShutdownParameters (00000380, 00000000): partial stub.
0009:fixme:thread:SetThreadStackGuarantee (0x33fc74): stub
0009:fixme:ntdll:EtwEventRegister ({e13c0d23-ccbc-4e12-931b-d9cc2eee27e4}, 0x7932a40c, 0x797293b0, 0x79764880) stub.
0009:fixme:ntdll:EtwEventRegister ({763fd754-7086-4dfe-95eb-c01a46faf4ca}, 0x7932a40c, 0x797292f0, 0x79729998) stub.
0009:fixme:ntdll:EtwEventRegister ({a669021c-c450-4609-a035-5af59af4df18}, 0x7932a40c, 0x79764890, 0x79764888) stub.
0009:fixme:ntdll:EtwEventRegister ({cc2bcbba-16b6-4cf3-8990-d74c2e8af500}, 0x7932a40c, 0x797648c0, 0x797292e8) stub.
0009:fixme:wer:WerRegisterRuntimeExceptionModule (L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscordacwks.dll", 0x79140000) stub!
0009:fixme:nls:LCIDToLocaleName unsupported flags 8000000
002d:fixme:service:QueryServiceConfig2W Level 6 not implemented
002d:fixme:service:QueryServiceConfig2W Level 6 not implemented
002d:fixme:service:QueryServiceConfig2W Level 6 not implemented
002d:fixme:service:QueryServiceConfig2W Level 6 not implemented
002d:fixme:service:QueryServiceConfig2W Level 6 not implemented`
and I get a prompt saying "CLR error: 80004005
The program will now terminate." When the osu installer has to start. The dependency install phase was bloated with errors, so that could be a problem.

**Comment by yurisuki** [comment]
On 19/05/14 04:26, Gergő Vári wrote:
> `002a:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
> 002a:fixme:heap:RtlSetHeapInformation (nil) 1 (nil) 0 stub
> 002a:err:winediag:gnutls_initialize failed to load libgnutls, no support for encryption
> 002d:fixme:process:SetProcessShutdownParameters (00000380, 00000000): partial stub.
> 0009:fixme:thread:SetThreadStackGuarantee (0x33fc74): stub
> 0009:fixme:ntdll:EtwEventRegister ({e13c0d23-ccbc-4e12-931b-d9cc2eee27e4}, 0x7932a40c, 0x797293b0, 0x79764880) stub.
> 0009:fixme:ntdll:EtwEventRegister ({763fd754-7086-4dfe-95eb-c01a46faf4ca}, 0x7932a40c, 0x797292f0, 0x79729998) stub.
> 0009:fixme:ntdll:EtwEventRegister ({a669021c-c450-4609-a035-5af59af4df18}, 0x7932a40c, 0x79764890, 0x79764888) stub.
> 0009:fixme:ntdll:EtwEventRegister ({cc2bcbba-16b6-4cf3-8990-d74c2e8af500}, 0x7932a40c, 0x797648c0, 0x797292e8) stub.
> 0009:fixme:wer:WerRegisterRuntimeExceptionModule (L"C:\\windows\\Microsoft.NET\\Framework\\v4.0.30319\\mscordacwks.dll", 0x79140000) stub!
> 0009:fixme:nls:LCIDToLocaleName unsupported flags 8000000
> 002d:fixme:service:QueryServiceConfig2W Level 6 not implemented
> 002d:fixme:service:QueryServiceConfig2W Level 6 not implemented
> 002d:fixme:service:QueryServiceConfig2W Level 6 not implemented
> 002d:fixme:service:QueryServiceConfig2W Level 6 not implemented
> 002d:fixme:service:QueryServiceConfig2W Level 6 not implemented`
> and I get a prompt saying "CLR error: 80004005
> The program will now terminate." When the osu installer has to start. The dependency install phase was bloated with errors, so that could be a problem.
>
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/yurisuki/osu-install/issues/11#issuecomment-492310371
no, it's wine being stupid and errors mean nothing.

**Comment by ghost** [comment]
Okay, but this CLR error has to do something with the .NET framework as I read about it. Might be not really installed?

**Comment by yurisuki** [comment]
> Okay, but this CLR error has to do something with the .NET framework as I read about it. Might be not really installed?

no, those are the errors i also get while i'm running the script and my osu works just fine.

**Comment by ghost** [comment]
but after the CLR error nothing really happens.

**Comment by ghost** [comment]
`Something has fucked up.
Log: Oh no, osu! didn't install.

Possibilities are:
You've changed the installation direction.
osu! installer
didn't run.
Some dependencies didn't install.

Try:
Run the script again
Leave the installation direction as it should be (defaultly selected by osu! installer)

If that didn't help try reporting it on GitHub. Thank you. <3` Now I'm left with this.

**Comment by yurisuki** [comment]
that's because an osu installer didn't run

**Comment by ghost** [comment]
Do you know what .NET version it needs? Maybe manually installing it.

**Comment by yurisuki** [comment]
> Do you know what .NET version it needs? Maybe manually installing it.

that's useless, because winetricks or wine will hang while the installation, because windows api sucks

**Comment by yurisuki** [comment]
> `Something has fucked up.
> Log: Oh no, osu! didn't install.
> 
> Possibilities are:
> You've changed the installation direction.
> osu! installer
> didn't run.
> Some dependencies didn't install.
> 
> Try:
> Run the script again
> Leave the installation direction as it should be (defaultly selected by osu! installer)
> 
> If that didn't help try reporting it on GitHub. Thank you. <3` Now I'm left with this.

https://www.reddit.com/r/osugame/comments/b3ia96/low_latency_osu_in_lutris_linux/ just use this way, wine and winetricks are so stupid, there's nothing i can do about this. the audio latency patch was applied to you system.

**Comment by ghost** [comment]
Okay, then I try that. Thanks!

**Comment by yurisuki** [comment]
> Okay, then I try that. Thanks!

no problem
