### ISSUE TITLE
[BUG] windows6.1-KB976932-X86.exe and windows6.1-KB976932-X86.exe: Access deined, I do not get a prompt to enter my sudo password

### ISSUE THREAD

**Issue by Viewedx** [yurisuki/osu-install-old#12]
(This is my first github post, forgive me lol)

I'm not able to install osu because of not getting a prompt to enter my sudo password meaning I cannot give access to the files in the title that need to be installed. 

windows6.1-KB976932-X86.exe: Permission denied
windows6.1-KB976932-X86.exe: Permission denied

Pop!_OS 19.04 (Ubuntu based)
Linux 5.0.0-15-generic
V2.1

**Comment by yurisuki** [comment]
On 19/06/06 12:00, Viewedx wrote:
> I'm not able to install osu because of not getting a prompt to enter my sudo password meaning I cannot give access to the files in the title that need to be installed.
>
> windows6.1-KB976932-X86.exe: Permission denied
> windows6.1-KB976932-X86.exe: Permission denied
>
> Pop!_OS 19.04 (Ubuntu based)
> Linux 5.0.0-15-generic
> V2.1
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/yurisuki/osu-install/issues/12

winetricks' fault, use this method https://www.reddit.com/r/osugame/comments/b3ia96/low_latency_osu_in_lutris_linux/

**Comment by yurisuki** [comment]
close

**Comment by yurisuki** [comment]
fix
