### ISSUE TITLE
osu-install.deb dependencies not met, even with apt-get -f install[BUG]

### ISSUE THREAD

**Issue by SuperShadowPlay** [yurisuki/osu-install-old#13]
When installing `osu-install.deb` it will fail with the following message:
```dpkg: dependency problems prevent configuration of osu-install:
 osu-install depends on wine32; however:
  Package wine32 is not installed.
 osu-install depends on wine64; however:
  Package wine64 is not installed.
 osu-install depends on libwine; however:
  Package libwine is not installed.
 osu-install depends on fonts-wine; however:
  Package fonts-wine is not installed.

dpkg: error processing package osu-install (--install):
 dependency problems - leaving unconfigured
Errors were encountered while processing:
 osu-install
```
So naturally the next thing to try and fix this is running `sudo apt-get -f install`, but that is entirely unhelpful because all it does it autoremove `osu-install` because it was not fully installed.

I've tried using the install script and I tried installing `wine` itself beforehand and that does not fix it either. Thanks in advance for any help.

Running on Ubuntu 16.04 with the latest updates.

**Comment by yurisuki** [comment]
you don't probably have i386 architecture
enter this in terminal:
```
sudo dpkg --add-architecture i386
wget -qO - https://dl.winehq.org/wine-builds/winehq.key | sudo apt-key add -
sudo apt-get update
sudo apt-get install --install-recommends winehq-stable
```

and after this:
```
git clone https://github.com/yurisuki/osu-install.git
cd osu-install
sudo make install
```
and run the script using `osu-install`

**Comment by SuperShadowPlay** [comment]
I'm new to wine so I did not know I had to enable 32 bit. After that your method of getting the official winehq repository didn't work, so I used [the winehq website](https://wiki.winehq.org/Ubuntu) to find out what was recommended for my machine. 

With wine installed I ran the `osu-install` script and had a combination of two previous issues. [I was not asked for my sudo password](https://github.com/yurisuki/osu-install/issues/12) and ultimately the script gave me an error similar to the error from from [this issue](https://github.com/yurisuki/osu-install/issues/5). While I was writing this, in my minimized console the script continued saying osu! was about to be installed and I should close it once opened to finish the installation. osu! didn't open so with no other option I pressed a key to continue and was greeted with this error:

`/usr/bin/osu-install: line 117: 10075 Illegal instruction     (core dumped) wine ~/Downloads/osui.exe`

The script then terminated with this message:

```
Something has fucked up.
Log: Oh no, osu! didn't install.
```

**Comment by yurisuki** [comment]
try `echo "export PATH=$PATH:/opt" >> ~/.bashrc"`

**Comment by SuperShadowPlay** [comment]
So that didn't work either, and now my pulseaudio daemon won't start.

I appreciate the help, but I'm going to move on by myself.

EDIT: /etc/pulse/default.pa being messed with by the installer was the culprit for the borked pulseaudio
