### ISSUE TITLE
[BUG] error: target not found: wine-osu winetricks wine-mono lib32-gn

### ISSUE THREAD

**Issue by miroesli** [yurisuki/osu-install-old#14]
**Describe the issue**
When using the osu-install through the AUR or by cloning the repository, the download fails at finding the wine package.

**To Reproduce**
1. Synchronize all package databases and update any if needed
```bash
$ sudo pacman -Syyuu 
```
2. Install osu-install
```bash
$ yay -S osu-install
```
3. Error
```bash
$ yay -S osu-install
==> Error: Could not find all required packages:
    wine (Wanted by: osu-install -> winetricks)
```

Alternatively with cloning the git repository
1. clone repo and make install
```bash
$ git clone https://github.com/yurisuki/osu-install.git
$ cd osu-install
$ sudo make install
mkdir -p /usr/bin
cp -f osu-install /usr/bin
chmod 755 /usr/bin/osu-installInstalled!
```
2. run the script
```bash
osu-install
```
3. Screenshot of error
![osu](https://user-images.githubusercontent.com/17695280/67260433-177ade00-f450-11e9-9a7f-50b22c340380.png)

**Distribution (OS):**
 - Distribution: arch linux
 - Kernel version: 5.3.7-arch1-1-ARCH
 - Version of your osu-install 2.1 (I think?)

**Comment by miroesli** [comment]
If it is just that the wine package needs to be changed from the script, I can submit a PR with the update if someone provides me with the correct package.

**Comment by undeadspez** [comment]
Have you tried https://aur.archlinux.org/packages/osu-install/ ?

**Comment by miroesli** [comment]
Seems to be working now. Didn't change anything, just attempted the download again after waiting a while. I'm guessing that after the pacman update there were some other dependencies that were not yet updated. Closing.

**Comment by Nioctris** [comment]
I also ran into this problem
