### ISSUE TITLE
[BUG] 0024:err:mscoree:expect_no_runtimes Process exited with a Mono runtime loaded.

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [yurisuki/osu-install-old#18]
**Describe the issue**
I installed osu using `osu-install` and then whenever i run `osu` i get this message

```
esmailelbob@esmailelbob🐸:~% osu
0070:err:vulkan:wine_vk_init Failed to load libvulkan.so.1.
0024:err:module:open_builtin_file failed to load .so lib "/usr/lib32/wine/l3codeca.acm.so"
0024:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
mono_os_sem_timedwait: mono_win32_wait_for_single_object_ex failed with error 998

abnormal program termination
0024:err:mscoree:expect_no_runtimes Process exited with a Mono runtime loaded.
```
**To Reproduce**
1. Install osu
2. try run the command `osu`

**Screenshots**

**Distribution (OS):**
 - Manajro
 -  5.10.2-2-MANJARO
 - i dont know, lol but i installed it yesterday

**Additional context**
Adding a way to uninstall the app is a good touch :P (nvm fount it! https://github.com/yurisuki/osu-install/wiki/Reverting-all-the-changes-that-the-script-has-made.)

**Comment by Michimuri** [comment]
I've same error with Arch kernel 5.4.98-1-lts
I think It may be related to the fact that I've installed gecko and mono wine.

However, the uninstall steps that are in the link you left doesn't delete the shorcuts (in terminal if I type osu, it stills recognizing and saying "~/osudir does not exist!" after enter). Ah...

**Comment by Michimuri** [comment]
SOLVED: To delete the command "osu" from terminal you have to delete /bin/osu which is the binary for it. Make sure you're doing this after finishing the steps in the link you commented.

**Comment by EsmailELBoBDev2** [comment]
Thanks for the tip! 
Now i just dual boot between windows for gaming and Linux for all other stuff xd
