### ISSUE TITLE
Manjaro xfce "Wine: Cannot find L"C:\\windows\\system32\\osu!.exe"

### ISSUE THREAD

**Issue by HelloCBA** [yurisuki/osu-install-old#2]
Every time I do the osu command to launch the game it never ends up opening and leads to the message in the title, the whole thing after typing the command is:
/usr/bin/osu: line 9: cd: /home/hello/osudir: No such file or directory
000b:fixme:winediag:start_process Wine Staging 3.12 is a testing version containing experimental patches.
000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
wine: cannot find L"C:\\windows\\system32\\osu!.exe"

**Comment by yurisuki** [comment]
On 19/04/13 10:21, HelloCBA wrote:
> Every time I do the osu command to launch the game it never ends up opening and leads to the message in the title, the whole thing after typing the command is:
> /usr/bin/osu: line 9: cd: /home/hello/osudir: No such file or directory
> 000b:fixme:winediag:start_process Wine Staging 3.12 is a testing version containing experimental patches.
> 000b:fixme:winediag:start_process Please mention your exact version when filing bug reports on winehq.org.
> wine: cannot find L"C:\\windows\\system32\\osu!.exe"
>
>
> --
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/yurisuki/osu-install/issues/2

ok, that's osudir not being found.

if you do 'ls ~/' in terminal, is there osudir?

**Comment by yurisuki** [comment]
https://github.com/yurisuki/osu-install/issues/3#issuecomment-483369614 the fix

**Comment by yurisuki** [comment]
Closing this, because it works, I've tried this on my Void Linux machine.
