### ISSUE TITLE
Unable to open after installation

### ISSUE THREAD

**Issue by ghost** [yurisuki/osu-install-old#3]
Hi, sorry if I'm not reporting this issue correctly, I'm also very new to Linux. I'm running Kubuntu. Upon typing osu in the terminal, I receive a large block of a repeating error.  

This is in essence what keeps repeating in the terminal for a while:
https://paste.ee/p/xmLnX

Here is an image to display how much the error repeats (notice the scrollbar size): 
![Screenshot_20190414_221757](https://user-images.githubusercontent.com/31361310/56092747-5fbcb080-5eaf-11e9-851d-db8160f574c2.png)

How should I go about fixing this?

**Comment by yurisuki** [comment]
try `sudo apt-get install libpng16-16` and then `ldconfig`

**Comment by ghost** [comment]
> try `sudo apt-get install libpng16-16` and then `ldconfig`

It seems I that already have libpng16-16 installed: 
![Screenshot_20190415_095806](https://user-images.githubusercontent.com/31361310/56101251-96c3ae00-5f11-11e9-9571-c4d8545dfb42.png)

Though it says that no such file or directory exists regarding osudir, I can see it in my home folder. Upon clicking it I'm greeted with this message again:
"Unable to run the command specified. The file or folder /home/myusername/osudir does not exist"

**Comment by yurisuki** [comment]
do you have more accounts on your pc?

do ‘ls ~/osudir’ and output it here.

**Comment by ghost** [comment]
I only have one account on my PC, though I am dual-booting. However, the drive that I am booting on is completely separate from my other drives. 
This is the output `/home/myusername/osudir`
https://i.imgur.com/7InlZMv.png

**Comment by yurisuki** [comment]
ok, it’s my fault, because one more guy also has this same thing. I’ll fix this when I’ll have an access to computer. For the fix do

‘sudo nano /bin/osu’ and change ~/osudir to ~/.wine-osu/drive_c/users/YOURUSERNAME/Local\ Settings/Application\ Data/osu\! 

ctrl-x to save, press y and enter to confirm.

replace YOURUSERNAME with your username. It should work when yoi do it. I’m sorry.

**Comment by ghost** [comment]
https://i.imgur.com/0VwxOC2.png

It doesn't seem to fix anything yet :/ 
The errors from above still occur. 

`‘sudo nano /bin/osu’ and change ~/osudir to ~/.wine-osu/drive_c/users/YOURUSERNAME/Local\ Settings/Application\ Data/osu!`

Am I supposed to be changing the path relative to the file location on my computer? If so, what specific file am I supposed to locate to get the path I can use to change?

**Comment by yurisuki** [comment]
replace cd ~/osudir with cd ~/THATTHING

**Comment by yurisuki** [comment]
THATTHING IS ~/.wine-osu/drive_c/users/YOURUSERNAME/Local\ Settings/Application\ Data/osu!

**Comment by ghost** [comment]
> replace cd ~/osudir with cd ~/THATTHING

As you can see in the screenshot I sent above, I already did that (unless I did it incorrectly)
Here is a clearer image: 
![HwcT2uK](https://user-images.githubusercontent.com/31361310/56191474-f0b09a80-601b-11e9-8e33-58cb819f87af.png)

**Comment by yurisuki** [comment]
and it still doesn’t work?

**Comment by ghost** [comment]
> and it still doesn’t work?

Nope, I still get the same errors as before

**Comment by yurisuki** [comment]
could you run the installing script now? it should be fixed now.

**Comment by yurisuki** [comment]
ALSO, before running the script remove osudir by `rm -rf ~/osudir ~/.wine_osu`

**Comment by yurisuki** [comment]
Closing this, because it works, I've tried this on my Void Linux machine.
