### ISSUE TITLE
How do I reverse all the changes that the script does?

### ISSUE THREAD

**Issue by sprite-1** [yurisuki/osu-install-old#4]
It kinda messed up pulseaudio and now I don't have any sound.

![image](https://user-images.githubusercontent.com/33685433/56658666-cae75d80-66cd-11e9-9a6d-b4ed21d6c9c1.png)
![image](https://user-images.githubusercontent.com/33685433/56658676-d20e6b80-66cd-11e9-8998-3ad7ee0c792d.png)
![image](https://user-images.githubusercontent.com/33685433/56658728-e9e5ef80-66cd-11e9-8f74-5e4154c09b24.png)

**Comment by yurisuki** [comment]
firstly, do `sudo fixcrack`, then `sudo rm /etc/pulse/daemon.conf.d/10-better-latency.conf`, and reboot.

**Comment by sprite-1** [comment]
I just finished rebooting after executing the commands but unfortunately, it's still the same

**Comment by yurisuki** [comment]
try `sudo rm /etc/security/limits.conf`

**Comment by sprite-1** [comment]
Okay now I'm stuck in a boot loop 😱

**Comment by yurisuki** [comment]
> Okay now I'm stuck in a boot loop

OOF, but I doubt removing limits.conf has caused this.

**Comment by sprite-1** [comment]
It was the only thing I did before rebooting though

**Comment by yurisuki** [comment]
well, i don't have any idea what could have caused it.

**Comment by yurisuki** [comment]
> It was the only thing I did before rebooting though

what kind of bootloop is that? take screenshot or smth

**Comment by yurisuki** [comment]
don’t worry, i also did an oopsie and removed important files in linux, and now i can’t login in https://imgur.com/a/AY96gOK 🤦‍♂️

**Comment by sprite-1** [comment]
Here is the boot loop in action

https://youtu.be/yjGBW7kJkK4

**Comment by yurisuki** [comment]
that’s an xorg looped

press ctrl+alt+f2, login and do ‘cat ~/.local/share/xorg/Xorg.*.log’ and output it here.

**Comment by sprite-1** [comment]
I was just about to say, pressing Ctrl + Alt + F2 doesn't work either 😅i t prompts me to log in but before I can type anything it loops already

**Comment by yurisuki** [comment]
actually, doesn’t elementary use wayland instead if xorg?

**Comment by sprite-1** [comment]
It uses Ubuntu 18.04 as base which uses xorg I think because Wayland was too unstable for an LTS release

**Comment by yurisuki** [comment]
i’m not sure what is the cause unless i have the log.

**Comment by yurisuki** [comment]
can you use installation usb, mount your drive with the bootlooped xorg in it and put here the output? it should be in ~/.local/share/xorg/Xorg.*.log

**Comment by sprite-1** [comment]
Okay **some progress**! I managed to find the USB I used to install elementary in the first place. I booted to it from BIOS and then restored `limits.conf`.

Thank goodness I didn't outright deleted the file because I felt uneasy about that so I instead just moved it somewhere else. So with the Live USB, I put it back in it's original place and rebooted and now I'm back to my desktop again but I still have the same problem (no sound)

**Comment by yurisuki** [comment]
also, i once had xorg loop, and disconnecting my graphics tablet fixed it, can you try it (if you have one)

**Comment by yurisuki** [comment]
so there’s something in limits.conf? ok, it wasn’t great idea having my script replace it with that sound fix. i’ll fix that. 

as for the sound fix, try updating your system and ‘sudo start-pulseaudio-x11’, i’ll also try to come up with some solution, but can’t edit the script atm, because i fucked up my own machine.

**Comment by yurisuki** [comment]
try this

rm -rf /tmp/pulse* ~/.pulse* ~/.config/pulse
pulseaudio -k
pulseaudio --start

**Comment by sprite-1** [comment]
I discovered something else, it isn't the contents of `limits.conf` that's important. It can be empty. What causes the boot loop is if the file itself is missing. So it can be empty as long as it's there in that path there will be no boot loop

**Comment by yurisuki** [comment]
> I discovered something else, it isn't the contents of `limits.conf` that's important. It can be empty. What causes the boot loop is if the file itself is missing. So it can be empty as long as it's there in that path there will be no boot loop

ok, have you tried the sound fixes above? https://github.com/yurisuki/osu-install/issues/4#issuecomment-486826068

**Comment by sprite-1** [comment]
Yeah, when I try to kill it, it gives me
```
E: [pulseaudio] main.c: Failed to kill daemon: No such process
```
Then when I try to start the process, it gives me
```
E: [pulseaudio] main.c: Daemon startup failed.
```

The removal of the pulseaudio-related files didn't return any errors

**Comment by yurisuki** [comment]
install alsamixer, and unmute the device using m key. 

then do ‘pulseaudio -vvv‘ and drop it here, thank you.

**Comment by sprite-1** [comment]
Umm it doesn't seem to be installable via `apt`, says it can't locate the package

As for the log, here it is

[pulse-log.txt](https://github.com/yurisuki/osu-install/files/3119032/pulse-log.txt)

**Comment by yurisuki** [comment]
> Umm it doesn't seem to be installable via `apt`, says it can't locate the package
> 
> As for the log, here it is
> 
> [pulse-log.txt](https://github.com/yurisuki/osu-install/files/3119032/pulse-log.txt)

yes, it's alsa related. it could be `alsa-utils` in apt

**Comment by sprite-1** [comment]
Okay I'm not sure what I'm supposed to do here. I'm pressing M key but don't see any visible changes either on the Terminal or elsewhere

![image](https://user-images.githubusercontent.com/33685433/56827448-6aa11900-6891-11e9-92de-4591d630d632.png)

**Comment by yurisuki** [comment]
> Okay I'm not sure what I'm supposed to do here. I'm pressing M key but don't see any visible changes either on the Terminal or elsewhere
> 
> ![image](https://user-images.githubusercontent.com/33685433/56827448-6aa11900-6891-11e9-92de-4591d630d632.png)

press f6 and select right sound card.

**Comment by sprite-1** [comment]
These are the only options available when I press F6

![image](https://user-images.githubusercontent.com/33685433/56832745-64199e00-689f-11e9-86f6-e90d2cd95af0.png)

**Comment by yurisuki** [comment]
idk, what to do. i'll try to come up with some solution.

**Comment by yurisuki** [comment]
I've tried many things, and I maybe came up with a solution. `rm ~/.config/pulse` should do it.

**Comment by sprite-1** [comment]
Deleting the pulse folder was one of the things I tried earlier on that didn't really work. I tried it just now and restarted just to be sure and it's still broken

**Comment by yurisuki** [comment]
> Deleting the pulse folder was one of the things I tried earlier on that didn't really work. I tried it just now and restarted just to be sure and it's still broken

have you tried reinstalling alsa and pulseaudio?

**Comment by sprite-1** [comment]
> have you tried reinstalling alsa and pulseaudio?

Yeah, I did it again just now to make sure and yeah it's still not working

It kinda sucks that I'm not that familiar with Linux so I can't help figure this thing out other than follow the tutorials littered through the web that ultimately doesn't seem to work
