### ISSUE TITLE
Illegal instruction (core dumped) (cant find a directory)

### ISSUE THREAD

**Issue by ghost** [yurisuki/osu-install-old#5]
When I execute the script, this text appaers on screen
```
mv: no se puede mover '/home/kaiju/opt/wine-osu/' a '/opt/wine-osu': Directory isnt empty
renamed '/home/kaiju/winetricks' -> '/usr/local/bin/winetricks'
```

But the script jumps it and tries the "Making wineprefix" and then this jumps out

Illegal instruction (core dumped)
```
ls: cant access to '/home/kaiju/.wine_osu/drive_c': There is no file or directory
grep: /home/kaiju/.wine_osu/*.reg: There is no file or directory
```

And then somehow, the scrip thinks everything went ok and tries to download the installer, but i get more and more errors.

**Comment by yurisuki** [comment]
do `sudo rm -rf /opt/wine-osu` and run the script again.

also, what distro you use?

**Comment by ghost** [comment]
Linux Mint.

Still happens, the "sudo mode" window does not ask for password it just skips it, and then keeps trying to install the wineprefix dependences
```
Illegal instruction (core dumped)
ls: cant access to '/home/kaiju/.wine_osu/drive_c': There is no file or directory
grep: /home/kaiju/.wine_osu/*.reg: There is no file or directory
wineserver: process not found
mscorsvw.exe: process not found
winetricks: process not found
mkdir: can create directory «/home/kaiju/Downloads»: File already exists
```
And then tries to download the osu installer
`/usr/bin/osu-install: línea 118:  3183 illegal instruction   (`core' generado) wine ~/Downloads/osui.exe`

Finally this drops
Something has fucked up.
Log: Oh no, osu! didn't install.

```
Possibilities are:
You've changed the installation direction.
osu! installer
didn't run.
Some dependencies didn't install.
```
Also, it seems that i dont have the volume settings. lulz

**Comment by yurisuki** [comment]
> Linux Mint.
> 
> Still happens, the "sudo mode" window does not ask for password it just skips it, and then keeps trying to install the wineprefix dependences
> 
> ```
> Illegal instruction (core dumped)
> ls: cant access to '/home/kaiju/.wine_osu/drive_c': There is no file or directory
> grep: /home/kaiju/.wine_osu/*.reg: There is no file or directory
> wineserver: process not found
> mscorsvw.exe: process not found
> winetricks: process not found
> mkdir: can create directory «/home/kaiju/Downloads»: File already exists
> ```
> 
> And then tries to download the osu installer
> `/usr/bin/osu-install: línea 118: 3183 illegal instruction (`core' generado) wine ~/Downloads/osui.exe`
> 
> Finally this drops
> Something has fucked up.
> Log: Oh no, osu! didn't install.
> 
> ```
> Possibilities are:
> You've changed the installation direction.
> osu! installer
> didn't run.
> Some dependencies didn't install.
> ```
> 
> Also, it seems that i dont have the volume settings. lulz

did you install wine from your package manager?
does `winetricks --help` output anything?

**Comment by ghost** [comment]
I have both wine, and winetricks installed.
winetricks --help command returns a list of commands

**Comment by yurisuki** [comment]
Do ‘echo "export PATH=\$PATH:/opt" >> ~/.bashrc’

**Comment by yurisuki** [comment]
and run osu-install again
