### ISSUE TITLE
Crash after successful osu! installation

### ISSUE THREAD

**Issue by dominikheinz** [yurisuki/osu-install-old#8]
After the installation osu! launched successfully.
However, I don't understand how I can start it properly after closing it?
When i do `wine osu!.exe` it crashes with this error:

```
[... a lot more lines ...]
0061:fixme:ole:Context_CC_ContextCallback (0x60cfb08/0x60cfb0c)->(0x791c8272, 0x322faf4, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
0061:fixme:ole:Context_CC_ContextCallback (0x60cfb08/0x60cfb0c)->(0x791c8272, 0x322faf4, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
0061:fixme:ole:Context_CC_ContextCallback (0x60cfb08/0x60cfb0c)->(0x791c8272, 0x322f970, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  12 (X_ConfigureWindow)
  Resource id in failed request:  0x6600073
  Serial number of failed request:  428
  Current serial number in output stream:  440
```

**Comment by yurisuki** [comment]
Do you use xorg or wayland?

**Comment by dominikheinz** [comment]
I believe xorg, but I am not sure. How can I check?

**Comment by yurisuki** [comment]
`ps -u $USER | egrep "Xorg|Wayland|wayland"`

**Comment by yurisuki** [comment]
> After the installation osu! launched successfully.
> However, I don't understand how I can start it properly after closing it?
> When i do `wine osu!.exe` it crashes with this error:
> 
> ```
> [... a lot more lines ...]
> 0061:fixme:ole:Context_CC_ContextCallback (0x60cfb08/0x60cfb0c)->(0x791c8272, 0x322faf4, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
> 0061:fixme:ole:Context_CC_ContextCallback (0x60cfb08/0x60cfb0c)->(0x791c8272, 0x322faf4, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
> 0061:fixme:ole:Context_CC_ContextCallback (0x60cfb08/0x60cfb0c)->(0x791c8272, 0x322f970, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
> X Error of failed request:  BadWindow (invalid Window parameter)
>   Major opcode of failed request:  12 (X_ConfigureWindow)
>   Resource id in failed request:  0x6600073
>   Serial number of failed request:  428
>   Current serial number in output stream:  440
> ```

also. you should run osu using `osu` command, because that uses the .wine_osu prefix.

**Comment by dominikheinz** [comment]
> `ps -u $USER | egrep "Xorg|Wayland|wayland"`
I don't get any output at all


> > After the installation osu! launched successfully.
> > However, I don't understand how I can start it properly after closing it?
> > When i do `wine osu!.exe` it crashes with this error:
> > ```
> > [... a lot more lines ...]
> > 0061:fixme:ole:Context_CC_ContextCallback (0x60cfb08/0x60cfb0c)->(0x791c8272, 0x322faf4, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
> > 0061:fixme:ole:Context_CC_ContextCallback (0x60cfb08/0x60cfb0c)->(0x791c8272, 0x322faf4, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
> > 0061:fixme:ole:Context_CC_ContextCallback (0x60cfb08/0x60cfb0c)->(0x791c8272, 0x322f970, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
> > X Error of failed request:  BadWindow (invalid Window parameter)
> >   Major opcode of failed request:  12 (X_ConfigureWindow)
> >   Resource id in failed request:  0x6600073
> >   Serial number of failed request:  428
> >   Current serial number in output stream:  440
> > ```
> 
> also. you should run osu using `osu` command, because that uses the .wine_osu prefix.
The osu command doesn't seem to be registered?
`bash: osu: command not found`

**Comment by yurisuki** [comment]
On 19/05/09 08:17, Domink Heinz wrote:
> > `ps -u $USER | egrep "Xorg|Wayland|wayland"`
> I don't get any output at all
>
>
> > > After the installation osu! launched successfully.
> > > However, I don't understand how I can start it properly after closing it?
> > > When i do `wine osu!.exe` it crashes with this error:
> > > ```
> > > [... a lot more lines ...]
> > > 0061:fixme:ole:Context_CC_ContextCallback (0x60cfb08/0x60cfb0c)->(0x791c8272, 0x322faf4, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
> > > 0061:fixme:ole:Context_CC_ContextCallback (0x60cfb08/0x60cfb0c)->(0x791c8272, 0x322faf4, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
> > > 0061:fixme:ole:Context_CC_ContextCallback (0x60cfb08/0x60cfb0c)->(0x791c8272, 0x322f970, {d7174f82-36b8-4aa8-800a-e963ab2dfab9}, 2, (nil))
> > > X Error of failed request:  BadWindow (invalid Window parameter)
> > >   Major opcode of failed request:  12 (X_ConfigureWindow)
> > >   Resource id in failed request:  0x6600073
> > >   Serial number of failed request:  428
> > >   Current serial number in output stream:  440
> > > ```
> >
> > also. you should run osu using `osu` command, because that uses the .wine_osu prefix.
> The osu command doesn't seem to be registered?
> `bash: osu: command not found`
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/yurisuki/osu-install/issues/8#issuecomment-490947764
'ps -u $USER' and try to find either wayland or xorg.

**Comment by dominikheinz** [comment]
Neither shows up in the list. For reference, if you are trying to reproduce the issue, I am running Manjaro + Gnome. From what I know Manjaro defaults Xorg.

**Comment by yurisuki** [comment]
do ‘export DISPLAY=:1 wine osu\!.exe’

if that doesn’t work, then try changing 1 to 0

**Comment by yurisuki** [comment]
On 19/05/09 08:39, Domink Heinz wrote:
> Neither shows up in the list. For reference, if you are trying to reproduce the issue, I am running Manjaro + Gnome. From what I know Manjaro defaults Xorg.
>
> --
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub:
> https://github.com/yurisuki/osu-install/issues/8#issuecomment-490956118
yes, manjaro is using xorg. please, take a notice that it's not my fault
neither script's fault. it's wine not being that great. sound patches
have been applied to your system, so you could also use the lutris
method which is here: https://www.reddit.com/r/osugame/comments/b3ia96/low_latency_osu_in_lutris_linux/
